variables:
  REPO_NAME: codeberg.org/video-prize-ranch/rimgo
  DOCKER_HOST: tcp://docker:2375

stages:
  - build
  - deploy

bin:
  stage: build
  needs: []
  image: golang:latest
  script:
    - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
    - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
    - CGO_ENABLED=0 go build -o $CI_PROJECT_DIR/rimgo
  artifacts:
    paths:
        - rimgo

docker:
  image: docker:20
  stage: build
  services:
    - name: docker:20-dind
      command: ["--experimental"]
  before_script:
    - mkdir -p ~/.docker/cli-plugins
    - wget -O ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.8.1/buildx-v0.8.1.linux-amd64
    - chmod +x ~/.docker/cli-plugins/docker-buildx
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker context create mybuilder
    - docker buildx create --use --name mybuilder mybuilder
    - docker buildx build --platform linux/amd64,linux/arm64 --push -t $CI_REGISTRY_IMAGE:latest .

deploy:
  image: alpine:latest
  stage: deploy
  needs: []
  before_script:
    - apk update && apk --no-cache add curl
    - wget -O - https://fly.io/install.sh | sh
  script:
    - /root/.fly/bin/flyctl deploy --detach
